#! python3
# pw.py - An insecure password locker program.

PASSWORDS = {'email': 'F7minlBDDuvMJuxESSKHFhTxFtjVB6',
             'blog': 'VmALvQyKAxiVH5G8v01if1MLZF3sdt',
             'luggage': '12345'}

import sys, pyperclip
if len(sys.argv) < 2:
    print('Usage: python pw.py [account] - copy account password')
    sys.exit()

account = sys.argv[1]      # first command line arg is the account name

if account in PASSWORDS:
    pyperclip.copy(PASSWORDS[account])
    print('Password for ' + account + ' copied to clipboard.')
else:
    print('There is no account named ' + account)
print('Would you like to enter a new account and password?')
answer = input()
if answer.lower() == 'y' or answer.lower() == 'yes':
	print('enter a new account name')
	new_account = input()
	print('enter a password for this account')
	new_password = input()
	PASSWORDS[new_account]=new_password
	print(PASSWORDS)
else:
	print('thank you and good bye')
